/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package multithreadsimple;

import javax.swing.JButton;

/**
 *
 * @author Less
 */
public class MainForm extends javax.swing.JFrame {

	/**
	 * Creates new form MainForm
	 */
	public MainForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startSimpleButton = new javax.swing.JButton();
        simpleProgressBar = new javax.swing.JProgressBar();
        simpleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        methodSyncProgressBar = new javax.swing.JProgressBar();
        startMethodSyncButton = new javax.swing.JButton();
        methodSyncLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startSimpleButton.setText("simple");
        startSimpleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startSimpleButtonMouseClicked(evt);
            }
        });

        simpleLabel.setText("0 %");

        startMethodSyncButton.setText("method sync");
        startMethodSyncButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMethodSyncButtonMouseClicked(evt);
            }
        });

        methodSyncLabel.setText("0 %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpleProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(simpleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startSimpleButton))
                    .addComponent(methodSyncProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(methodSyncLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startMethodSyncButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSimpleButton)
                    .addComponent(simpleLabel))
                .addGap(10, 10, 10)
                .addComponent(simpleProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startMethodSyncButton)
                    .addComponent(methodSyncLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(methodSyncProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSimpleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startSimpleButtonMouseClicked
        //((JButton) evt.getComponent()).setEnabled(false);
		if(startSimpleButton.isEnabled()){
			startComputeThread();
		}
    }//GEN-LAST:event_startSimpleButtonMouseClicked


    private void startMethodSyncButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMethodSyncButtonMouseClicked
        if(startMethodSyncButton.isEnabled()){
			startMethoodSyncThread();
		}
    }//GEN-LAST:event_startMethodSyncButtonMouseClicked

	/**
	 * Example of syncronyze of threads
	 */
	public void startMethoodSyncThread(){
		MultiThreadSource source = new MultiThreadSource();
		
		for(int i=0; i < 5; ++i){
			source.addComputer(new ActiveThread(1000));
		}
		
		ProcessIndicator indicator = new ProcessIndicator(source);
		indicator.setInterface(methodSyncProgressBar, startMethodSyncButton, methodSyncLabel);
		Thread indicatorThread = new Thread(indicator);
		
		indicatorThread.start();
		source.begin();
	}
	
	/**
	 * Example of simple multithread work
	 */
	public void startComputeThread(){
		SimpleThread compThread = new SimpleThread();
		ProcessIndicator indicator = new ProcessIndicator(compThread);
		indicator.setInterface(simpleProgressBar, startSimpleButton, simpleLabel);
		Thread indicatorThread = new Thread(indicator);
		
		compThread.start();
		indicatorThread.start();
		
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel methodSyncLabel;
    private javax.swing.JProgressBar methodSyncProgressBar;
    private javax.swing.JLabel simpleLabel;
    private javax.swing.JProgressBar simpleProgressBar;
    private javax.swing.JButton startMethodSyncButton;
    private javax.swing.JButton startSimpleButton;
    // End of variables declaration//GEN-END:variables
}
