/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rsshttpclient;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Less
 */
public class RssHttpClient extends javax.swing.JFrame {
	
	RssLoader loader = null;

	/**
	 * Creates new form RssHttpClient
	 */
	public RssHttpClient() {
		initComponents();
		
		Path dir = Paths.get("1.txt");
		System.out.println(dir.toAbsolutePath().toString());
		
		urlSrc.setText("http://elementy.ru/rss/news/mathematics");
		
		String xsl;
		Path xslPath = Paths.get("view.format.xsl");
		if(! Files.exists(xslPath)){
			System.out.println("No xsl file found!");
			return;
		}
		try {
			xsl = new String(Files.readAllBytes(xslPath));
		} catch (IOException ex) {
			System.out.println("read xsl file problem!");
			System.out.println(ex);
			return;
		}
		loader = new RssLoader(contentEditorPane, xsl);
		//loader.setXslSource(xsl);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlSrc = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        getButton = new javax.swing.JButton();
        editorScrollPane = new javax.swing.JScrollPane();
        contentEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urlSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlSrcActionPerformed(evt);
            }
        });
        urlSrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                urlSrcKeyTyped(evt);
            }
        });

        statusLabel.setText("status");

        getButton.setText("Go");
        getButton.setFocusable(false);
        getButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getButtonMouseClicked(evt);
            }
        });
        getButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getButtonActionPerformed(evt);
            }
        });

        contentEditorPane.setContentType("text/html"); // NOI18N
        editorScrollPane.setViewportView(contentEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editorScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(urlSrc, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlSrc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusLabel))
                    .addComponent(getButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editorScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlSrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urlSrcActionPerformed

    private void getButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getButtonMouseClicked
        if(loader == null){
			statusLabel.setText("No Loader");
			return;
		}
		String uri = urlSrc.getText();
		loader.start(uri);
    }//GEN-LAST:event_getButtonMouseClicked

    private void urlSrcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlSrcKeyTyped
        // control url validation ?
		
		// Enter
		
    }//GEN-LAST:event_urlSrcKeyTyped

    private void getButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RssHttpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RssHttpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RssHttpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RssHttpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RssHttpClient().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane contentEditorPane;
    private javax.swing.JScrollPane editorScrollPane;
    private javax.swing.JButton getButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField urlSrc;
    // End of variables declaration//GEN-END:variables
}
